name: Robot Quet Van Ban So KHCN Dien Bien

on:
  schedule:
    - cron: '0 * * * *' # Chạy tự động mỗi giờ một lần
  workflow_dispatch: # Nút bấm chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lay code ve
        uses: actions/checkout@v3

      - name: 2. Cai dat Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Cai dat thu vien
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Chay Robot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python robot.py
